name = "uranus"

[variables]
version = "0.0.1"

[task.build]
description = "Build the project."
command = "go build -o $name cmd/uranus/main.go"

[task.test]
command = "go test ./..."
depends = [
    "format"
]

[task.format]
command = "go fmt ./..."

